//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipFood.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbFoodyEntities : DbContext
    {
        public dbFoodyEntities()
            : base("name=dbFoodyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbAdmin> tbAdmin { get; set; }
        public virtual DbSet<tbChiTietDonHang> tbChiTietDonHang { get; set; }
        public virtual DbSet<tbDanhGia> tbDanhGia { get; set; }
        public virtual DbSet<tbDanhMuc> tbDanhMuc { get; set; }
        public virtual DbSet<tbDonHang> tbDonHang { get; set; }
        public virtual DbSet<tbKhachHang> tbKhachHang { get; set; }
        public virtual DbSet<tbKhuyenMai> tbKhuyenMai { get; set; }
        public virtual DbSet<tbLoaiHinhThanhToan> tbLoaiHinhThanhToan { get; set; }
        public virtual DbSet<tbMonAn> tbMonAn { get; set; }
        public virtual DbSet<tbMonAnKhuyenMai> tbMonAnKhuyenMai { get; set; }
        public virtual DbSet<tbQuanAn> tbQuanAn { get; set; }
        public virtual DbSet<tbShipper> tbShipper { get; set; }
        public virtual DbSet<tbTinNhan> tbTinNhan { get; set; }
        public virtual DbSet<tbThongTinDatHang> tbThongTinDatHang { get; set; }
        public virtual DbSet<tbUser> tbUser { get; set; }
    }
}
